### ISSUE TITLE
Why is Flash Messenger is drawing root route?

### ISSUE THREAD

**Issue by mccormjt** [aeberlin/flash_messenger#1]
Hi @aeberlin,

Why are you drawing a root route in config/routes.rb?
If you try to include this gem in an existing project that already designates their root to a custom controller and action then you get a rails error complaining its being defined twice:

`Invalid route name, already in use: 'root'  (ArgumentError)`

Thanks,
John

**Comment by aeberlin** [comment]
Will fix tonight and create a release tag.

Cheers

On Wednesday, January 27, 2016, John notifications@github.com wrote:

> Hi @aeberlin https://github.com/aeberlin,
> 
> Why are you drawing a root route in config/routes.rb?
> If you try to include this gem in an existing project that already
> designates their root to a custom controller and action then you get a
> rails error complaining its being defined twice:
> 
> Invalid route name, already in use: 'root' (ArgumentError)
> 
> Thanks,
> John
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/arkbot/flash_messenger/issues/1.

## 

## 

adam eberlin +1 312 725 2757

**Comment by aeberlin** [comment]
Resolved in https://github.com/arkbot/flash_messenger/releases/tag/v0.0.2.
