### ISSUE TITLE
Bump Gem Version & Redeploy to RubyGems.org plz

### ISSUE THREAD

**Issue by mccormjt** [aeberlin/flash_messenger#3]
Hi again Adam,

sorry to bother you again.
Would you mind bumping the gem version and republishing it when you get a chance!

Thanks!

**Comment by aeberlin** [comment]
@mccormjt Please see the changes in #4. They may be breaking, although the differences are in line with recent changes to `rspec-expectations` and `#match?`. I will merge after travis passes and push a release up. Cheers.

**Comment by aeberlin** [comment]
Pushed, cheers.

https://rubygems.org/gems/flash_messenger
